
export interface Campaign {
  id: string;
  name: string;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  utm_content?: string;
  utm_term?: string;
  pixel_id?: string;
  whatsapp_number?: string;
  event_type?: 'contact' | 'lead' | 'page_view' | 'sale';
  custom_message?: string;
  company_title?: string;
  company_subtitle?: string;
  logo_url?: string;
  redirect_type?: 'form' | 'whatsapp';
  active?: boolean;
  created_at?: string;
  user_id?: string;
  client_id?: string;
  pixel_integration_type?: string;
  conversion_api_enabled?: boolean;
  facebook_access_token?: string;
  test_event_code?: string;
  custom_audience_pixel_id?: string;
  tracking_domain?: string;
  external_id?: string;
  data_processing_options?: string[];
  data_processing_options_country?: number;
  data_processing_options_state?: number;
  advanced_matching_enabled?: boolean;
  server_side_api_enabled?: boolean;
  evolution_api_key?: string;
  evolution_instance_name?: string;
  evolution_base_url?: string;
  webhook_callback_url?: string;
  auto_create_leads?: boolean;
  conversion_keywords?: string[];
  cancellation_keywords?: string[];
}
