// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbrpboxxhlwmenrajdji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdicnBib3h4aGx3bWVucmFqZGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjExMDAsImV4cCI6MjA2MTY5NzEwMH0.2zuTiMpOVAWHlTq2hBzwYkJz14gl7GJLQD-dGABp_lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);